export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    UPDATE_CART_ITEM: "UPDATE_CART_ITEM",
    CLEAR_CART: "CLEAR_CART",
    FETCH_PRODUCTS_ERROR: "FETCH_PRODUCTS_ERROR",
    BUY_PRODUCT:"BUY_PRODUCT",
    SET_ORDER_DETAILS:"SET_ORDER_DETAILS"
};